### ISSUE TITLE
How to use this in Flutter?

### ISSUE THREAD

**Issue by PeterTF656** [MohammedNoureldin/aws-url-signer#1]
Dear Dev, 

Thank you for sharing. However, I did not find any documentation on this. How to use this in Flutter?

**Comment by MohammedNoureldin** [comment]
Hello Peter, excuse me for not adding Docs for this. I intended to use it only for me internally.

You just need to call this function:

```
getSignedWebSocketUrl(apiId, region, stage, accessKey, secretKey, sessionToken);
```

`apiId` is the Id of your WebSocket API.
`region`, `stage` are self explanatory.
`accessKey`, `secretKey`, and `sessionToken` can be fetched as described in this link:

https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter

**Comment by MohammedNoureldin** [comment]
@PeterTF656 Was this very simple description helpful? If no please feel free to comment and reopen this issue.

**Comment by PeterTF656** [comment]
Dear Mohammed,

I appreciate your kind response. I have fixed my issue. Thanks a lot!
